### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by StephanVerbeeck** [google/gxui#178]
>go get -u github.com/google/gxui/...
# github.com/google/gxui/drivers/gl
C:\Users\Stephan\go\src\github.com\google\gxui\drivers\gl\driver.go:191:12: assignment mismatch: 2 variables but c.window.Window.GetClipboardString returns 1 values

line 191 should be

		str = c.window.GetClipboardString()

**Comment by Kvaz1r** [comment]
As written in readme this package is no longer maintained. If your want to upgrade existing application you can try to use nelsam's [fork](https://github.com/nelsam/gxui) , otherwise there is [A list of Go GUI/graphics/image related projects](https://github.com/go-graphics/go-gui-projects) with several interesting options.
