### ISSUE TITLE
drop down list is blank/empty

### ISSUE THREAD

**Issue by tones111** [google/gxui#56]
It could be that I'm not using it correctly, but if I modify the list sample to create a drop down list in place of the existing list (and comment out the call to SetOrientation) it doesn't render the list.  I see an empty box in place of the list but clicking on it doesn't show the list of items from the adapter.

Could you add an example of a drop down list to the lists sample please?

**Comment by ben-clayton** [comment]
Hi @tones111. The drop-down list requires a bubble overlay assigned in order to draw the list outside the bounds of the control. Simply create bubble overlay with ```theme.CreateBubbleOverlay()```, add after all other controls to the window, and set it to the drop down list with ```SetBubbleOverlay```.

I am working on a DropDownList sample, I just haven't finished it yet. If you have something, please feel free to make a pull-request.

Many thanks.
